apiVersion: v1
kind: Service
metadata:
  name: qwen36-burst-svc
  labels:
    app: vllm-burst-scaling
    model: qwen36-35b-a3b
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
spec:
  ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    model: qwen36-35b-a3b
