apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hybrid-nodes-gateway
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
      - eks-hybrid-nodes-gateway
  selector:
    matchLabels:
      app.kubernetes.io/name: eks-hybrid-nodes-gateway
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
