apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: hybrid-pod-allow-vpc
  namespace: default
spec:
  endpointSelector:
    matchLabels:
      app: vllm-burst-scaling
      tier: hybrid
  ingress:
    - fromEntities:
        - world
        - remote-node
      toPorts:
        - ports:
            - port: "8000"
              protocol: TCP
